nats:
  config:
    jetstream:
      enabled: true
      memStorage:
        enabled: true
        size: 1Gi
      fileStorage:
        enabled: false
    cluster:
      enabled: false  # single-node for demo
  container:
    image:
      tag: "2.10.14-alpine"
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  podTemplate:
    topologySpreadConstraints: {}
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    labels:
      app: nats
      version: "2.10.14"
      component: messaging

  natsBox:
    enabled: false  # natsBox has no runAsNonRoot — blocked by Kyverno in demo

  promExporter:
    enabled: true
    port: 7778

  service:
    enabled: true
    ports:
      nats:
        enabled: true
      leafnodes:
        enabled: false
      websocket:
        enabled: true
