apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sensor-simulator
  namespace: platform
spec:
  project: devops-demo
  source:
    repoURL: https://github.com/rhorba/CTS
    targetRevision: main
    path: services/sensor-simulator/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: platform
spec:
  project: devops-demo
  source:
    repoURL: https://github.com/rhorba/CTS
    targetRevision: main
    path: services/api-gateway/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-sink
  namespace: platform
spec:
  project: devops-demo
  source:
    repoURL: https://github.com/rhorba/CTS
    targetRevision: main
    path: services/data-sink/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-consumer
  namespace: platform
spec:
  project: devops-demo
  source:
    repoURL: https://github.com/rhorba/CTS
    targetRevision: main
    path: services/enterprise-consumer/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
