apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: platform
spec:
  project: devops-demo
  source:
    repoURL: https://github.com/rhorba/CTS
    targetRevision: main
    path: charts/mosquitto
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: platform
spec:
  project: devops-demo
  source:
    repoURL: https://github.com/rhorba/CTS
    targetRevision: main
    path: charts/nats
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: platform
spec:
  project: devops-demo
  source:
    repoURL: https://github.com/rhorba/CTS
    targetRevision: main
    path: charts/redpanda
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda-connect
  namespace: platform
spec:
  project: devops-demo
  source:
    repoURL: https://github.com/rhorba/CTS
    targetRevision: main
    path: charts/redpanda-connect
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-mq
  namespace: platform
spec:
  project: devops-demo
  source:
    repoURL: https://github.com/rhorba/CTS
    targetRevision: main
    path: charts/ibm-mq
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
