apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: {{ .Release.Namespace }}
  labels: {{ toYaml .Values.podLabels | nindent 4 }}
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      port: {{ .Values.service.mqttPort }}
      targetPort: mqtt
    - name: websocket
      port: {{ .Values.service.websocketPort }}
      targetPort: websocket
